services:
  - type: web
    name: quajo
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn Quajo.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: quajo_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: Quajo.settings.production
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: quajo_db
    databaseName: quajo
    user: quajo
